apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: katka-ggoo 
  janus-idp.io/tekton: katka-ggoo
  backstage.io/kubernetes-id: katka-ggoo
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: katka-ggoo
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml