apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: katka-ggoo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: katka-ggoo 
  name: katka-ggoo
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: katka-ggoo
    weight: 100 
