apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: katka-ggoo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: katka-ggoo 
  name: katka-ggoo
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: katka-ggoo 
